const {chromium} = require(process.env.METIS_PLAYWRIGHT_MODULE);
const fs = require('fs');
(async () => {
  const browser = await chromium.launch({headless:true, executablePath:process.env.METIS_BROWSER_EXECUTABLE});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  const base = process.env.METIS_BROWSER_BASE;
  const output = process.env.METIS_BROWSER_OUTPUT;
  const manifest = await (await page.request.get(base+'/browser-manifest')).json();
  await page.goto(base+'/login');
  await page.locator('[name=username]').fill('author');
  await page.locator('[name=password]').fill('fixture-only');
  await Promise.all([page.waitForURL(base+'/'), page.locator('button[type=submit]').click()]);
  const expected = ['Inleveren','Bronselectie','Review','Publicatie','Documenten'];
  const titles = await page.locator('.home-tile-title').allTextContents();
  if (JSON.stringify(titles)!==JSON.stringify(expected)) throw Error('workflow order '+JSON.stringify(titles));
  await page.screenshot({path:output+'/home.png',fullPage:true});
  await page.goto(base+'/ingest');
  await page.locator('[name=file]').setInputFiles({name:'fixture.html',mimeType:'text/html',
    buffer:Buffer.from('<html><body><p>Gebruik geen zalf.</p></body></html>')});
  await page.locator('[name=title]').fill('Source browser proof');
  await page.locator('[name=version]').fill('1');
  await page.locator('[name=date]').fill('2026-10-09');
  await page.locator('[name=family]').fill('fixture');
  await page.locator('[name=review_mode]').selectOption('single');
  await page.locator('[name=primary_reviewer]').selectOption(manifest.reviewer);
  await Promise.all([page.waitForURL('**/source-selection?**'), page.locator('#ingest-submit').click()]);
  const sid = new URL(page.url()).searchParams.get('document');
  if (await page.locator('select[name=document]').inputValue()!==sid) throw Error('selected document');
  await page.getByRole('button',{name:'Starten',exact:true}).waitFor();
  if (!(await page.locator('[role=status]').allTextContents()).some(t=>t.includes('nog niet gestart'))) throw Error('receipt auto-started');
  await page.screenshot({path:output+'/received.png',fullPage:true});
  await page.reload();
  await page.getByRole('button',{name:'Starten',exact:true}).click();
  await page.waitForURL('**/source-selection?**');
  await page.getByRole('link',{name:'Naar Review',exact:true}).waitFor({timeout:15000});
  await page.screenshot({path:output+'/formed.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.reload();
  if (await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)) throw Error('mobile overflow');
  await page.screenshot({path:output+'/mobile.png',fullPage:true});
  await page.getByRole('link',{name:'Naar Review',exact:true}).click();
  await page.waitForURL('**/review?**');
  if (errors.length) throw Error('script errors '+JSON.stringify(errors));
  fs.writeFileSync(output+'/browser-result.json',JSON.stringify({layout:titles,selected:sid,
    receiptDidNotStart:true,explicitStart:true,reviewOpened:true,mobileOverflow:false,pageErrors:errors},null,2));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
