const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
(async()=>{
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8818/login');
await page.locator('[name=username]').fill('author');await page.locator('[name=password]').fill('fixture-only');
await Promise.all([page.waitForURL('**/'),page.locator('button[type=submit]').click()]);
const expected=['Inleveren','Bronselectie','Review','Publicatie','Documenten'];
const titles=await page.locator('.home-tile-title').allTextContents();
if(JSON.stringify(titles)!==JSON.stringify(expected))throw Error('layout '+JSON.stringify(titles));
await page.screenshot({path:'evidence/availability/home.png',fullPage:true});
await page.goto('http://127.0.0.1:8818/ingest');
await page.locator('[name=file]').setInputFiles({name:'fixture.html',mimeType:'text/html',buffer:Buffer.from('<html><body><p>Gebruik geen zalf.</p></body></html>')});
await page.locator('[name=title]').fill('Bronselectie bewijs');await page.locator('[name=version]').fill('1');
await page.locator('[name=date]').fill('2026-10-08');await page.locator('[name=family]').fill('fixture');
await page.locator('[name=review_mode]').selectOption('single');
await Promise.all([page.waitForURL('**/source-selection?**'),page.locator('#ingest-submit').click()]);
const sid=new URL(page.url()).searchParams.get('document');
if(await page.locator('select[name=document]').inputValue()!==sid)throw Error('automatic selection');
await page.getByRole('button',{name:'Starten',exact:true}).waitFor();
await page.screenshot({path:'evidence/availability/received.png',fullPage:true});
await page.getByRole('button',{name:'Starten',exact:true}).click();
await page.waitForURL('**/source-selection?**');
await page.reload();await page.getByRole('link',{name:'Naar Review',exact:true}).waitFor({timeout:10000});
await page.screenshot({path:'evidence/availability/formed.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.reload();
await page.screenshot({path:'evidence/availability/selection-mobile.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw Error('mobile overflow');
if(errors.length)throw Error('page errors '+JSON.stringify(errors));
console.log(JSON.stringify({layout:titles,autoSelected:true,startAndReview:true,mobileOverflow:false,pageErrors:errors}));
await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
